### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by ColDog** [ColDog/bld#3]
Services are docker containers that are spun up on the same network as a test
container when the tests will be run. Environment variables and basic configs
should be configurable.

Example:

```yaml
steps:
- name: Test
  services:
  - image: "{{ .Steps.Build.Image }}"
```
